[template]
keys        = [ "services/zookeeper/ip_port" ]
owner       = "root"
mode        = "0644"
src         = "server.properties.tmpl"
dest        = "/opt/kafka/config/server.properties"
reload_cmd  = "/usr/bin/supervisorctl restart kafka"
